[package]
name = "edumdns_server"
version = "0.1.0"
edition = "2024"

[dependencies]
aya = "0.13.1"
rustls = { version = "0.23.32", features = ["ring"] }
rustls-pki-types = "1.12.0"

edumdns_core = { workspace = true }
edumdns_db = { workspace = true }
thiserror = {workspace = true}
tokio = {workspace = true}
log = {workspace = true}
diesel-async = {workspace = true}
ipnetwork = {workspace = true}
uuid = {workspace = true}
hickory-proto = {workspace = true}
futures = {workspace = true}
