#app_log_level="info"
#all_log_level="info"

[database]
connection_string="postgres://edumdns:edumdns@192.168.0.10/edumdns"

#[server]
#hostnames=["[::]:5000"]

#[server.ebpf]
#proxy_ipv4=
#proxy_ipv6=
#pin_location="/sys/fs/bpf/edumdns"

#[server.tls]
#cert_path=
#key_path=

#[server.connection]
#global_timeout=10
#buffer_size=1000

#[server.transmit]
#max_transmit_subnet_size=512
#transmit_repeat_delay_multiplicator=5

[web]
session_cookie="Zm4aXgY1SJv9OnbwYgbhixYtb9R/ki6O1dIbcXS3X5ES+7QYdSyrfvat5wEsKmotNS9n17jEdNkhj7XZpnE="
#hostnames=["[::]:8000"]

#site_url="locahost"
#static_files_dir="edumdns_web"

#[web.oidc]
#client_id=
#client_secret=
#issuer=
#callback_url=
#new_users_admin=

#[web.tls]
#cert_path=
#key_path=

#[web.external_auth_database]
#connection_string=
#auth_query=

#[web.session]
#session_expiration=2592000
#last_visit_deadline=604800
#use_secure_cookie=true
