#app_log_level="info"
#all_log_level="info"

[database]
connection_string="postgres://edumdns:edumdns@localhost/edumdns"

[server]
#hostnames=["[::]:5000"]
#channel_buffer_capacity=1000

#[server.ebpf]
#proxy_ipv4=
#proxy_ipv6=
#pin_location="/sys/fs/bpf/edumdns"

#[server.tls]
#cert_path=
#key_path=

[server.connection]
#global_timeout=10
#buffer_capacity=1000

#[server.transmit]
#max_transmit_subnet_size=512
#transmit_repeat_delay_multiplicator=5

[web]
# Mandatory cookie secret, generate with `openssl rand -base64 32`
session_cookie="<secret>"
#hostnames=["[::]:8000"]
#site_url="locahost"
#static_files_dir="edumdns_web"

#[web.oidc]
#client_id=
#client_secret=
#issuer=
#callback_url=
#new_users_admin=

#[web.limits]
#payload_limit=17179869184
#form_limit=16777216
#probe_ping_interaval=1

#[web.tls]
#cert_path=
#key_path=

#[web.external_auth_database]
#connection_string=
#auth_query=

#[web.session]
#session_expiration=2592000
#last_visit_deadline=604800
#use_secure_cookie=true
